/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dcrs.gui;
import dcrs.railway.Locomotive;
import dcrs.railway.Railway;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author Christophe
 */
public class Manual_GUI extends javax.swing.JFrame {

    public Locomotive locomotive;
    public Railway railway;
    
    /**
     * Creates new form RailwayGUI
     */
    public Manual_GUI(Railway railway) {
        
        initComponents();
        this.railway=railway;
        this.setVisible(true);
        cbChoiceLoco.addItem("No Loco");
        cbChoiceLoco.addItem("Choose Locomotive");
        for(Locomotive each : railway.getLocomotives())
            cbChoiceLoco.addItem(each.getId());      
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLight = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        cbChoiceLoco = new javax.swing.JComboBox();
        jlSpeed = new javax.swing.JLabel();
        jlForward = new javax.swing.JLabel();
        jlBackward = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsSpeed = new javax.swing.JSlider();
        pnDirLight = new javax.swing.JPanel();
        jrbOnLight = new javax.swing.JRadioButton();
        jrbOffLight = new javax.swing.JRadioButton();
        jlLight = new javax.swing.JLabel();
        jbEmergency = new javax.swing.JButton();
        jbEmergencyContinue = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbChoiceLoco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbChoiceLoco.setMaximumRowCount(4);
        cbChoiceLoco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Locomotive" }));
        cbChoiceLoco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbChoiceLoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChoiceLocoActionPerformed(evt);
            }
        });

        jlSpeed.setBackground(new java.awt.Color(255, 204, 204));
        jlSpeed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSpeed.setText("Speed of the Locomotive");

        jlForward.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlForward.setText("Forward");

        jlBackward.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlBackward.setText("Backward");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dcrs/gui/CHOOCHOO!!!!.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jsSpeed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsSpeed.setForeground(new java.awt.Color(0, 0, 0));
        jsSpeed.setMajorTickSpacing(5);
        jsSpeed.setMaximum(30);
        jsSpeed.setMinimum(-30);
        jsSpeed.setMinorTickSpacing(1);
        jsSpeed.setPaintLabels(true);
        jsSpeed.setPaintTicks(true);
        jsSpeed.setValue(0);
        jsSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsSpeedStateChanged(evt);
            }
        });

        pnDirLight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        jrbOnLight.setBackground(new java.awt.Color(255, 255, 51));
        bgLight.add(jrbOnLight);
        jrbOnLight.setText("On");
        jrbOnLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOnLightActionPerformed(evt);
            }
        });

        bgLight.add(jrbOffLight);
        jrbOffLight.setText("Off");
        jrbOffLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOffLightActionPerformed(evt);
            }
        });

        jlLight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlLight.setText("Lights");

        javax.swing.GroupLayout pnDirLightLayout = new javax.swing.GroupLayout(pnDirLight);
        pnDirLight.setLayout(pnDirLightLayout);
        pnDirLightLayout.setHorizontalGroup(
            pnDirLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDirLightLayout.createSequentialGroup()
                .addComponent(jlLight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbOnLight)
                .addGap(12, 12, 12)
                .addComponent(jrbOffLight)
                .addContainerGap())
        );
        pnDirLightLayout.setVerticalGroup(
            pnDirLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDirLightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDirLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLight)
                    .addComponent(jrbOnLight)
                    .addComponent(jrbOffLight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbEmergency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbEmergency.setForeground(new java.awt.Color(255, 0, 51));
        jbEmergency.setText("EMERGENCY STOP");
        jbEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmergencyStopActionPerformed(evt);
            }
        });

        jbEmergencyContinue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbEmergencyContinue.setForeground(new java.awt.Color(0, 153, 0));
        jbEmergencyContinue.setText("CONTINUE");
        jbEmergencyContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmergencyContinueActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Manual Locomotive Control");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Reset speed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlBackward)
                        .addGap(2, 2, 2)
                        .addComponent(jsSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jlForward)
                        .addGap(248, 248, 248))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbChoiceLoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnDirLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jlSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEmergencyContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(29, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(cbChoiceLoco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(pnDirLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jbEmergency)
                        .addGap(31, 31, 31)
                        .addComponent(jbEmergencyContinue)))
                .addGap(11, 11, 11)
                .addComponent(jlSpeed)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlForward)
                    .addComponent(jlBackward)
                    .addComponent(jsSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEmergencyStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmergencyStopActionPerformed
        // TODO add your handling code here: Done
        for(Locomotive loco : railway.getLocomotives())
        {
            loco.emergencyStop();
        }
    }//GEN-LAST:event_jbEmergencyStopActionPerformed

    private void jsSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsSpeedStateChanged
        // TODO add your handling code here: Done
        if(locomotive != null) {
            if(jsSpeed.getValue()>0){
                locomotive.setDirection(0);
                locomotive.reachSpeed(jsSpeed.getValue());
            }else{
                locomotive.setDirection(1);
                locomotive.reachSpeed((jsSpeed.getValue())*(-1));
            }
        }
    }//GEN-LAST:event_jsSpeedStateChanged

    private void jbEmergencyContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmergencyContinueActionPerformed
        // TODO add your handling code here: Done
        for(Locomotive loco : railway.getLocomotives())
        {
            loco.emergencyContinue();
        }
    }//GEN-LAST:event_jbEmergencyContinueActionPerformed

    private void jrbOffLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOffLightActionPerformed
        // TODO add your handling code here: Done
        locomotive.setLight(false);   
    }//GEN-LAST:event_jrbOffLightActionPerformed

    private void jrbOnLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOnLightActionPerformed
        // TODO add your handling code here: Done
        locomotive.setLight(true);
    }//GEN-LAST:event_jrbOnLightActionPerformed

    private void cbChoiceLocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChoiceLocoActionPerformed
        //modification
        if(cbChoiceLoco.getSelectedItem()==null) return;
        if(!cbChoiceLoco.getSelectedItem().toString().equals("Choose Locomotive")){
            locomotive = railway.getLocomotiveById(cbChoiceLoco.getSelectedItem().toString());
            //System.out.println(cbChoiceLoco.getSelectedItem());
            jsSpeed.setValue(locomotive.getDesiredSpeed());
        }
    }//GEN-LAST:event_cbChoiceLocoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jsSpeed.setValue(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manual_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manual_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manual_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manual_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * 
         * Create and display the form
         */
        new Manual_GUI(Railway.instance());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLight;
    private javax.swing.JComboBox cbChoiceLoco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbEmergency;
    private javax.swing.JButton jbEmergencyContinue;
    private javax.swing.JLabel jlBackward;
    private javax.swing.JLabel jlForward;
    private javax.swing.JLabel jlLight;
    private javax.swing.JLabel jlSpeed;
    private javax.swing.JRadioButton jrbOffLight;
    private javax.swing.JRadioButton jrbOnLight;
    private javax.swing.JSlider jsSpeed;
    private javax.swing.JPanel pnDirLight;
    // End of variables declaration//GEN-END:variables
}
